import Foundation
import AppKit

struct AndroidExporter {
    /// Exports common launcher icons into both mipmap-* and drawable-* folders.
    /// Output structure:
    /// Android/
    ///   mipmap-mdpi/ic_launcher.png ...
    ///   drawable-mdpi/ic_launcher.png ...
    static func exportLauncherIcons(from image: NSImage, to outDir: URL) throws {
        try FileManager.default.createDirectory(at: outDir, withIntermediateDirectories: true)

        let densities: [(name: String, px: Int)] = [
            ("mdpi", 48),
            ("hdpi", 72),
            ("xhdpi", 96),
            ("xxhdpi", 144),
            ("xxxhdpi", 192)
        ]

        for (name, px) in densities {
            for root in ["mipmap-\(name)", "drawable-\(name)"] {
                let dir = outDir.appendingPathComponent(root, isDirectory: true)
                try FileManager.default.createDirectory(at: dir, withIntermediateDirectories: true)

                let fileURL = dir.appendingPathComponent("ic_launcher.png")
                guard let png = ImageResizer.renderPNG(from: image, pixelSize: px) else {
                    throw IconForgeError.invalidImage
                }
                try png.write(to: fileURL)
            }
        }

        // Optional: a simple README
        let readme = outDir.appendingPathComponent("README.txt")
        let text = "Generated by IconForge. Copy folders into your Android project under app/src/main/res/.\n"
        try text.data(using: .utf8)?.write(to: readme)
    }
}
