import Foundation
import AppKit

// MARK: - AndroidExporter

struct AndroidExporter {

    // MARK: - Density table

    /// 标准 Android 密度桶
    private static let densities: [(name: String, px: Int)] = [
        ("mdpi",    48),
        ("hdpi",    72),
        ("xhdpi",   96),
        ("xxhdpi",  144),
        ("xxxhdpi", 192),
    ]

    // MARK: - Public API

    /// 导出完整的 Android 图标资源集合。
    ///
    /// 输出结构：
    /// ```
    /// Android/
    ///   mipmap-mdpi/
    ///     ic_launcher.png
    ///     ic_launcher_round.png
    ///   mipmap-hdpi/ ...
    ///   ...
    ///   mipmap-xxxhdpi/
    ///   play_store_512.png          ← Google Play 商店图标
    ///   README.txt
    /// ```
    static func exportLauncherIcons(from image: NSImage, to outDir: URL) throws {
        try FileManager.default.createDirectory(at: outDir, withIntermediateDirectories: true)

        for (name, px) in densities {
            let dir = outDir.appendingPathComponent("mipmap-\(name)", isDirectory: true)
            try FileManager.default.createDirectory(at: dir, withIntermediateDirectories: true)

            // ic_launcher.png（方形）
            guard let png = ImageResizer.renderPNG(from: image, pixelSize: px) else {
                throw IconForgeError.invalidImage
            }
            try png.write(to: dir.appendingPathComponent("ic_launcher.png"))

            // ic_launcher_round.png（圆形裁剪）
            guard let roundPng = renderRoundPNG(from: image, pixelSize: px) else {
                throw IconForgeError.invalidImage
            }
            try roundPng.write(to: dir.appendingPathComponent("ic_launcher_round.png"))
        }

        // Google Play 商店图标（512×512，JPEG 或 PNG 均可，这里输出 PNG）
        guard let storePng = ImageResizer.renderPNG(from: image, pixelSize: 512) else {
            throw IconForgeError.invalidImage
        }
        try storePng.write(to: outDir.appendingPathComponent("play_store_512.png"))

        // README
        let readme = outDir.appendingPathComponent("README.txt")
        let text = """
        Generated by IconKit.

        Copy the mipmap-* folders into your Android project under:
            app/src/main/res/

        play_store_512.png → upload to Google Play Console as the app icon.

        ic_launcher.png       – standard square launcher icon
        ic_launcher_round.png – circular launcher icon (Android 7.1+)
        """
        try text.data(using: .utf8)?.write(to: readme)
    }

    // MARK: - Round icon

    /// 渲染圆形裁剪的 PNG（透明背景）。
    private static func renderRoundPNG(from image: NSImage, pixelSize: Int) -> Data? {
        guard pixelSize > 0 else { return nil }

        guard let colorSpace = CGColorSpace(name: CGColorSpace.sRGB) else { return nil }
        guard let cgCtx = CGContext(
            data: nil,
            width: pixelSize,
            height: pixelSize,
            bitsPerComponent: 8,
            bytesPerRow: 0,
            space: colorSpace,
            bitmapInfo: CGImageAlphaInfo.premultipliedLast.rawValue
        ) else { return nil }

        cgCtx.interpolationQuality = .high

        // 圆形裁剪路径
        let rect = CGRect(x: 0, y: 0, width: pixelSize, height: pixelSize)
        cgCtx.addEllipse(in: rect)
        cgCtx.clip()

        // 绘制图片（aspect-fill，填满圆形）
        let nsCtx = NSGraphicsContext(cgContext: cgCtx, flipped: false)
        NSGraphicsContext.saveGraphicsState()
        NSGraphicsContext.current = nsCtx
        nsCtx.imageInterpolation = .high

        let srcSize = image.size
        guard srcSize.width > 0, srcSize.height > 0 else {
            NSGraphicsContext.restoreGraphicsState()
            return nil
        }

        // aspect-fill：取较大缩放比，使图片填满正方形
        let scale = max(CGFloat(pixelSize) / srcSize.width, CGFloat(pixelSize) / srcSize.height)
        let drawSize = CGSize(width: srcSize.width * scale, height: srcSize.height * scale)
        let drawOrigin = CGPoint(
            x: (CGFloat(pixelSize) - drawSize.width)  / 2,
            y: (CGFloat(pixelSize) - drawSize.height) / 2
        )

        image.draw(in: CGRect(origin: drawOrigin, size: drawSize),
                   from: .zero,
                   operation: .sourceOver,
                   fraction: 1.0,
                   respectFlipped: false,
                   hints: [.interpolation: NSImageInterpolation.high])

        NSGraphicsContext.restoreGraphicsState()

        guard let cgImage = cgCtx.makeImage() else { return nil }
        let rep = NSBitmapImageRep(cgImage: cgImage)
        rep.size = CGSize(width: pixelSize, height: pixelSize)
        return rep.representation(using: .png, properties: [:])
    }
}
